# nginx proxy address - http://172.17.0.1:8085

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - freshrss
    ports:
      - "8085:8085"
    environment:
      TZ: ${TZ:-America/New_York}
      DATABASE_URL: postgresql://${DB_USER_NAME:-freshrss}:${DB_USER_PASS:-changeme_db_password}@freshrss-db:5432/${DB_CREATE_DATABASE_NAME:-freshrss}
    volumes:
      - ./rootfs/data/freshrss:/var/www/data
      - ./rootfs/config/freshrss:/config
    depends_on:
      - freshrss-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085"]
      interval: 30s
      timeout: 10s
      retries: 3

  freshrss-db:
    image: postgres:16-alpine
    container_name: freshrss-db
    restart: unless-stopped
    logging: *default-logging
    networks:
      - freshrss
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-freshrss}
      POSTGRES_USER: ${DB_USER_NAME:-freshrss}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
    volumes:
      - ./rootfs/db/postgres/freshrss:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  freshrss:
    external: false
